# Generated by Django 3.2.9 on 2021-12-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanage', '0002_studentmanage_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmanage',
            name='StudentID',
            field=models.TextField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
