# Generated by Django 3.2.9 on 2021-12-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanage', '0003_studentmanage_studentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmanage',
            old_name='StudentID',
            new_name='studentID',
        ),
    ]
