# Generated by Django 3.2.9 on 2021-12-28 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentmanage', '0004_rename_studentid_studentmanage_studentid'),
        ('stc', '0002_auto_20211228_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clabsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateabsent', models.DateField()),
                ('classID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stc.stc')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmanage.studentmanage')),
            ],
            options={
                'db_table': 'clabsent',
            },
        ),
    ]
