# Generated by Django 3.2.9 on 2021-12-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clabsent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clabsent',
            name='case',
            field=models.TextField(default=22, max_length=100),
            preserve_default=False,
        ),
    ]
