# Generated by Django 3.2.9 on 2021-12-30 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clabsent', '0002_clabsent_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clabsent',
            name='case',
        ),
    ]
