# Generated by Django 3.2.9 on 2021-12-30 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clabsent', '0003_remove_clabsent_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clabsent',
            old_name='classID',
            new_name='classname',
        ),
    ]
