# Generated by Django 3.2.9 on 2021-12-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stcID', models.TextField(max_length=100)),
                ('stcname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'stc',
            },
        ),
    ]
