# Generated by Django 3.2.9 on 2021-12-28 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stc',
            old_name='stcID',
            new_name='classID',
        ),
        migrations.RenameField(
            model_name='stc',
            old_name='stcname',
            new_name='classname',
        ),
    ]
