# Generated by Django 3.2.9 on 2021-12-30 02:58

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("studentmanage", "0005_remove_studentmanage_course"),
        ("stc", "0002_auto_20211228_0734"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asscl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "No",
                    models.IntegerField(verbose_name=django.db.models.fields.AutoField),
                ),
                (
                    "classID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stc.stc"
                    ),
                ),
                (
                    "studentID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studentmanage.studentmanage",
                    ),
                ),
                ("dateabsent", models.DateField()),
            ],
            options={
                "db_table": "asscl",
            },
        ),
    ]
