# Generated by Django 3.2.9 on 2021-12-31 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assigncl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asscl',
            old_name='No',
            new_name='dateassign',
        ),
    ]
