# Generated by Django 3.2.9 on 2021-12-31 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assigncl', '0002_rename_no_asscl_dateassign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asscl',
            name='dateassign',
        ),
    ]
