# Generated by Django 3.2.9 on 2021-12-31 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assigncl', '0003_remove_asscl_dateassign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asscl',
            old_name='dateabsent',
            new_name='assigndate',
        ),
    ]
